server:
  port: 8088
spring:
  application:
    name: BankingLedgerSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
