server:
  port: 8088
spring:
  application:
    name: BankingLedgerSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/bls
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop
